import type { CouncilDecision } from "./types.js";

export function renderCouncilDecisionMarkdown(decision: CouncilDecision): string {
  const lines: string[] = [];

  lines.push("# Model Council Decision");
  lines.push("");
  lines.push("Generated by: model-council");
  lines.push("");

  // Add degraded mode warning if applicable
  if (decision.metadata?.degraded) {
    lines.push("> **Warning:** This council decision used degraded mode. Some model outputs failed, were repaired, or synthesis fell back.");
    lines.push("");
  }

  lines.push(`**Mode:** ${decision.mode}`);
  lines.push(`**Confidence:** ${decision.confidence}`);
  lines.push(`**Decision ID:** ${decision.decisionId}`);
  lines.push("");

  // Add system warnings if any
  if (decision.metadata?.warnings && decision.metadata.warnings.length > 0) {
    lines.push("## System Warnings");
    for (const warning of decision.metadata.warnings) {
      lines.push(`- ${warning}`);
    }
    lines.push("");
  }

  lines.push("## Recommended Plan");
  lines.push(decision.recommendedPlan.summary);
  lines.push("");

  if (decision.recommendedPlan.steps.length > 0) {
    lines.push("## Steps");
    for (let i = 0; i < decision.recommendedPlan.steps.length; i++) {
      lines.push(`${i + 1}. ${decision.recommendedPlan.steps[i]}`);
    }
    lines.push("");
  }

  if (decision.consensus.agreements.length > 0) {
    lines.push("## Agreements");
    for (const agreement of decision.consensus.agreements) {
      lines.push(`- ${agreement}`);
    }
    lines.push("");
  }

  if (decision.consensus.disagreements.length > 0) {
    lines.push("## Disagreements");
    for (const disagreement of decision.consensus.disagreements) {
      lines.push(`- ${disagreement}`);
    }
    lines.push("");
  }

  if (decision.consensus.unknowns.length > 0) {
    lines.push("## Unknowns");
    for (const unknown of decision.consensus.unknowns) {
      lines.push(`- ${unknown}`);
    }
    lines.push("");
  }

  if (decision.implementationGuidance.filesToEdit.length > 0) {
    lines.push("## Files to Edit");
    for (const file of decision.implementationGuidance.filesToEdit) {
      lines.push(`- \`${file.path}\`: ${file.action} — ${file.reason}`);
    }
    lines.push("");
  }

  if (decision.implementationGuidance.testsToRun.length > 0) {
    lines.push("## Verification / Tests to Run");
    for (const test of decision.implementationGuidance.testsToRun) {
      lines.push(`- ${test}`);
    }
    lines.push("");
  }

  if (decision.implementationGuidance.guardrails.length > 0) {
    lines.push("## Guardrails");
    for (const guardrail of decision.implementationGuidance.guardrails) {
      lines.push(`- ${guardrail}`);
    }
    lines.push("");
  }

  if (decision.modelNotes.length > 0) {
    lines.push("## Model Notes");
    for (const note of decision.modelNotes) {
      lines.push(`### ${note.model}`);
      lines.push(`**Stance:** ${note.stance}`);
      if (note.keyRisks.length > 0) {
        lines.push(`**Key Risks:** ${note.keyRisks.join(", ")}`);
      }
      lines.push("");
    }
  }

  lines.push("## Handoff Prompt");
  lines.push(decision.handoffPrompt);

  lines.push("");
  lines.push("***");
  lines.push("");

  lines.push("This council decision is advisory. The main Pi coding model must still inspect the code, apply changes, and verify with tests.");

  return lines.join("\n");
}
