import type { SecondOpinionInput } from "./types.js";
import { buildSecondOpinionPrompt } from "./prompts.js";
import { callOpenRouterChat, extractJsonObject } from "./openrouterClient.js";
import { repairModelOpinion, validateModelOpinion } from "./structuredOutput.js";
import { withTimeout } from "./retry.js";
import { loadSettings } from "./settings.js";
import { OpinionSetupError } from "./types.js";

export async function runSecondOpinion(args: {
  input: SecondOpinionInput;
  signal?: AbortSignal;
  onStatus?: (message: string) => void;
  cwd?: string;
  isProjectTrusted?: boolean;
}): Promise<{
  opinion: {
    stance: string;
    recommendedApproach: string;
    steps: string[];
    filesToConsider: Array<{ path: string; reason: string; suggestedAction: string }>;
    risks: string[];
    verification: string[];
    confidence: "low" | "medium" | "high";
  };
  rawText: string;
  markdown: string;
}> {
  const cwd = args.cwd ?? process.cwd();
  const isProjectTrusted = args.isProjectTrusted ?? false;

  // ── Load settings ────────────────────────────────────────────────────────
  const settings = await loadSettings(cwd, isProjectTrusted);

  if (!settings) {
    throw new OpinionSetupError(
      "Second opinion model is not configured.\n\n" +
      "Run /opinion-settings to:\n" +
      "  1. Select your preferred provider\n" +
      "  2. Choose a model\n" +
      "  3. Save settings\n\n" +
      "Alternatively, run /council-settings which also configures the opinion model.",
    );
  }

  const apiKey = settings.openRouter.apiKey;
  const opinionModelId = settings.opinion.modelId;

  // ── Validate input ───────────────────────────────────────────────────────
  if (!args.input.problem || args.input.problem.trim().length === 0) {
    throw new Error("Problem is required and must be non-empty");
  }

  args.onStatus?.("Second opinion: querying model...");

  // Build prompt
  const { systemPrompt, userPrompt } = buildSecondOpinionPrompt(args.input);

  let rawText: string;

  try {
    rawText = await withTimeout(
      (childSignal) => callOpenRouterChat({
        apiKey,
        model: opinionModelId,
        systemPrompt,
        userPrompt,
        signal: childSignal,
      }),
      settings.options.modelTimeoutMs,
      args.signal,
    );
  } catch (error) {
    throw new Error(
      `Opinion model ${opinionModelId} failed: ${error instanceof Error ? error.message : String(error)}`,
      { cause: error },
    );
  }

  args.onStatus?.("Second opinion: parsing response...");

  let parsed: ReturnType<typeof validateModelOpinion>["value"];
  let warnings: string[] = [];

  try {
    const jsonObj = extractJsonObject(rawText);
    const validation = validateModelOpinion(jsonObj);

    if (validation.ok) {
      parsed = validation.value!;
    } else {
      const repaired = repairModelOpinion(jsonObj, rawText);
      parsed = repaired.value!;
      warnings = repaired.warnings ?? [];
    }
  } catch {
    parsed = {
      stance: "Direct response",
      recommendedApproach: rawText.substring(0, 500),
      steps: [],
      filesToConsider: [],
      risks: [],
      verification: [],
      confidence: "medium" as const,
    };
    warnings = ["Response was not structured JSON, showing raw response."];
  }

  args.onStatus?.("Second opinion: rendering markdown...");

  const markdown = renderSecondOpinionMarkdown(parsed, args.input, warnings);

  args.onStatus?.("Second opinion: complete");

  return { opinion: parsed, rawText, markdown };
}

function renderSecondOpinionMarkdown(
  opinion: {
    stance: string;
    recommendedApproach: string;
    steps: string[];
    filesToConsider: Array<{ path: string; reason: string; suggestedAction: string }>;
    risks: string[];
    verification: string[];
    confidence: "low" | "medium" | "high";
  },
  input: SecondOpinionInput,
  warnings: string[],
): string {
  const lines: string[] = [];

  lines.push("# Second Opinion");
  lines.push("");
  lines.push(`Generated by: ${input.mode ?? "general"} model (model-council)`);
  lines.push("");

  if (warnings.length > 0) {
    for (const warning of warnings) {
      lines.push(`> **Note:** ${warning}`);
    }
    lines.push("");
  }

  lines.push(`**Problem:** ${input.problem}`);
  if (input.currentUnderstanding) {
    lines.push(`**Your Understanding:** ${input.currentUnderstanding}`);
  }
  lines.push(`**Confidence:** ${opinion.confidence}`);
  lines.push("");

  if (opinion.stance) {
    lines.push("## Stance");
    lines.push(opinion.stance);
    lines.push("");
  }

  lines.push("## Recommended Approach");
  lines.push(opinion.recommendedApproach);
  lines.push("");

  if (opinion.steps.length > 0) {
    lines.push("## Steps");
    for (let i = 0; i < opinion.steps.length; i++) {
      lines.push(`${i + 1}. ${opinion.steps[i]}`);
    }
    lines.push("");
  }

  if (opinion.filesToConsider.length > 0) {
    lines.push("## Files to Consider");
    for (const file of opinion.filesToConsider) {
      lines.push(`- \`${file.path}\`: ${file.suggestedAction} — ${file.reason}`);
    }
    lines.push("");
  }

  if (opinion.risks.length > 0) {
    lines.push("## Key Risks");
    for (const risk of opinion.risks) {
      lines.push(`- ${risk}`);
    }
    lines.push("");
  }

  if (opinion.verification.length > 0) {
    lines.push("## Verification");
    for (const verification of opinion.verification) {
      lines.push(`- ${verification}`);
    }
    lines.push("");
  }

  lines.push("***");
  lines.push("");
  lines.push("This is a single-model second opinion. For multi-perspective analysis, use /council.");

  return lines.join("\n");
}
